# Generated by Django 5.2.7 on 2025-11-08 22:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('main_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Main Image')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark yes for property to be featured on Homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Extra Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='listings.property')),
            ],
        ),
    ]
