# Generated by Django 5.2.7 on 2025-12-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_property_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Enter the FontAwesome icon class.', max_length=150),
        ),
    ]
