# Generated by Django 5.2.7 on 2025-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Paste only the numeric latitude value. Right-click on Google Maps => Copy the first set of numbers and paste in here.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Paste only the numeric longitude value. Right-click on Google Maps => Copy the second set of numbers and paste in here.', max_digits=9, null=True),
        ),
    ]
