# Generated by Django 5.2.7 on 2025-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='area_description',
            field=models.TextField(blank=True, help_text='Description of the area.', null=True),
        ),
    ]
