# Generated by Django 5.2.7 on 2025-12-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expires_at',
        ),
    ]
